# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c93c725667b4ba7bd4a7024a418896a49873d526269d982f496b5e2fb0baec4fa2ad819d979cb0e5e5e3cb02acf3d770931d94933a8881951b82c8e82cdb7ad9

test:
  secret_key_base: 527a01ae2aed2ad765ca42c5a932ef54ed5633becce465d86c94f882ad79b0c60b1ccc1ab69790417289b574e9cbabd5580d8c2a68a654ad668299306471f2be

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
